name: AIOStreams
version: "2.6.1"            # bump when you update the image tag
slug: aiostreams
description: >
  Self-hosted Stremio super-addon that aggregates many providers into one endpoint.
url: https://github.com/Viren070/AIOStreams
arch:
  - aarch64                 # Raspberry Pi 5 & other 64-bit ARM boards
startup: application
boot: auto
image: ghcr.io/viren070/aiostreams:v2.6.1
ports:
  "3000/tcp": 8469
ports_description:
  "3000/tcp": "AIOStreams API / Web UI"
webui: http://[HOST]:[PORT:3000]/
map:
  - type: share
    read_only: false
options: {}
schema: {}
