name: AIOStreams
slug: aiostreams
description: >
  Self-hosted Stremio super-addon that aggregates many providers into one endpoint.
version: "2.6.1"              # must match the upstream tag
url: https://github.com/Viren070/AIOStreams
image: ghcr.io/viren070/aiostreams  # ← NO tag here!
arch:
  - aarch64
startup: application
boot: auto
ports:
  "3000/tcp": 8469
ports_description:
  "3000/tcp": "AIOStreams API / Web UI"
webui: http://[HOST]:[PORT:3000]/
map:
  - type: share
    read_only: false
options: {}
schema: {}
