 name: AIOStreams
-version: "v2.6.1"        # keep whatever the latest tag is
-image: ghcr.io/viren070/aiostreams:v2.6.1
+version: "2.6.1"         # or "v2.6.1" — just match the upstream tag
+image: ghcr.io/viren070/aiostreams
 arch:
   - aarch64
startup: application
boot: auto
image: ghcr.io/viren070/aiostreams:v2.6.1
ports:
  "3000/tcp": 8469
ports_description:
  "3000/tcp": "AIOStreams API / Web UI"
webui: http://[HOST]:[PORT:3000]/
map:
  - type: share
    read_only: false
options: {}
schema: {}
